# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\jvish\OneDrive\Desktop\UTS-Project\ui_files\modeltype.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(563, 516)
        dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        dialog.setStyleSheet("background-color:rgb(1, 78, 144)\n"
"")
        self.newmodel = QtWidgets.QPushButton(dialog)
        self.newmodel.setGeometry(QtCore.QRect(150, 160, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Fluent Icons")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.newmodel.setFont(font)
        self.newmodel.setStyleSheet("background-color: rgb(200, 217, 231);\n"
"border-radius: 35px;\n"
"border-width: 2opx;\n"
"color: rgb(1, 78, 144);")
        self.newmodel.setObjectName("newmodel")
        self.trainedmodel = QtWidgets.QPushButton(dialog)
        self.trainedmodel.setGeometry(QtCore.QRect(150, 260, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Fluent Icons")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.trainedmodel.setFont(font)
        self.trainedmodel.setStyleSheet("background-color: rgb(200, 217, 231);\n"
"border-radius: 35px;\n"
"border-width: 2opx;\n"
"color: rgb(1, 78, 144);")
        self.trainedmodel.setObjectName("trainedmodel")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 541, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 36pt \"Times New Roman\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ExitButton = QtWidgets.QPushButton(dialog)
        self.ExitButton.setGeometry(QtCore.QRect(150, 350, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Fluent Icons")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.ExitButton.setFont(font)
        self.ExitButton.setStyleSheet("background-color: rgb(200, 217, 231);\n"
"border-radius: 35px;\n"
"border-width: 2opx;\n"
"color: rgb(1, 78, 144);")
        self.ExitButton.setObjectName("ExitButton")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.newmodel.setText(_translate("dialog", "New Model"))
        self.trainedmodel.setText(_translate("dialog", "Trained Model"))
        self.label_2.setToolTip(_translate("dialog", "<html><head/><body><p align=\"justify\">Predictive Maintenance</p></body></html>"))
        self.label_2.setText(_translate("dialog", "<html><head/><body><p><span style=\" font-size:22pt;\">CHOOSE YOUR MODEL</span></p></body></html>"))
        self.ExitButton.setText(_translate("dialog", "Exit"))
